# Generated by Django 5.2.16 on 2026-07-13 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rating_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('experience_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('price_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('availability_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('response_rate_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('favorites_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('activity_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_score', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=7)),
                ('last_calculated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_score', to='providers.providerprofile')),
            ],
        ),
    ]
